---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: Ubuntu1804
    image: ubuntu:18.04

provisioner:
  name: ansible
  options:
    v: true
  env:
    ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: goss
  lint:
    name: yamllint
