---
- hosts: all
  gather_facts: no
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-zipstream)
      changed_when: False

- name: Converge
  hosts: all
  roles:
    - role: domoticz

  post_tasks:
    - name: start domoticz in docker via shell
      shell: /opt/domoticz/domoticz/domoticz --www 8080 >/dev/null 2>&1 &

    - name: Wait for Domoticz to succesfully restart
      wait_for:
        port: "{{ domoticz_port }}"

    - name: Test Domoticz HTTP webinterface
      uri:
        url: "http://{{ inventory_hostname }}:{{ domoticz_port }}"

    # - name: Wait for Domoticz to succesfully restart
    #   wait_for:
    #     port: "{{ domoticz_https_port }}"
    #   when: domoticz_https

    # - name: Test Domoticz HTTPS webinterface
    #   uri:
    #     url: "https://{{ inventory_hostname }}:{{ domoticz_https_port }}"
    #     validate_certs: false
    #   when: domoticz_https

    # - name: Grab system Logs
    #   shell: "journalctl -xn || cat /var/log/messages || cat /var/log/syslog"
    #   environment:
    #     - PAGER: cat
    #   changed_when: false
    #   ignore_errors: true
